# Generated by Django 5.2.8 on 2025-12-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="lecture_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
