# Generated by Django 5.2.8 on 2025-12-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_attendance_lecture_time_attendance_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT_ONLINE", "Present (Online)"),
                    ("PRESENT_OFFLINE", "Present (Offline)"),
                    ("ABSENT", "Absent"),
                ],
                max_length=20,
            ),
        ),
    ]
