# Generated by Django 5.2.8 on 2025-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="classroom_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="days_of_week",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated days e.g. Mon,Tue,Wed",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="zoom_host_account",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="zoom_host_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="zoom_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="zoom_meeting_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="zoom_meeting_passcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
