# Generated by Django 5.2.8 on 2025-12-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_batch_classroom_name_batch_days_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("NEFT", "NEFT"),
                    ("RTGS", "RTGS"),
                    ("CHEQUE", "Cheque"),
                ],
                max_length=10,
            ),
        ),
    ]
