# Generated by Django 5.2.8 on 2025-12-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_fee_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="total_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(
                choices=[
                    ("Java", "Java"),
                    ("Python", "Python"),
                    ("Cloud Computing", "Cloud Computing"),
                    ("Data Analytics", "Data Analytics"),
                    ("DSA", "DSA"),
                    ("C Programming", "C Programming"),
                    ("C++", "C++"),
                    ("Data Science", "Data Science"),
                    ("UI/UX", "UI/UX"),
                    ("Cyber Security", "Cyber Security"),
                    ("Agentic AI", "Agentic AI"),
                    ("Data Engineering", "Data Engineering"),
                    ("Software Testing", "Software Testing"),
                ],
                max_length=100,
            ),
        ),
    ]
