# Generated by Django 5.2.8 on 2025-12-02 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_student_total_fees_alter_student_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="registration_no",
        ),
    ]
