# Generated by Django 5.2.8 on 2025-12-02 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_student_registration_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
