# Generated by Django 5.2.8 on 2026-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_student_enrollment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="fees_told",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="lead_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOT", "Hot"),
                    ("WARM", "Warm"),
                    ("COLD", "Cold"),
                    ("ENROLLED", "Enrolled"),
                ],
                default="WARM",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="next_followup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(
                choices=[
                    ("Data Science", "Data Science"),
                    ("Data Analytics", "Data Analytics"),
                    ("Full Stack Python", "Full Stack Python"),
                    ("Full Stack Java", "Full Stack Java"),
                    ("MERN Stack Development", "MERN Stack Development"),
                    ("Cloud & DevOps", "Cloud & DevOps"),
                    ("Software Testing", "Software Testing"),
                    ("DSA", "DSA"),
                    ("C Lang", "C Lang"),
                    ("C++", "C++"),
                    ("Core Python", "Core Python"),
                    ("Core Java", "Core Java"),
                    ("SQL", "SQL"),
                    ("Power BI", "Power BI"),
                    ("Tableau", "Tableau"),
                    ("React JS", "React JS"),
                    ("HTML/CSS/JavaScript", "HTML/CSS/JavaScript"),
                    ("Django", "Django"),
                    ("Spring", "Spring"),
                    ("CyberSecurity", "CyberSecurity"),
                    ("Agentic AI", "Agentic AI"),
                    ("Data Engineering", "Data Engineering"),
                    ("Data Science + Data Analytics", "Data Science + Data Analytics"),
                ],
                max_length=100,
            ),
        ),
    ]
